#!/bin/bash
echo "SSH Upload Script"
echo "================="
echo ""
echo "Command format:"
echo "scp favicon.ico favicon-16x16.png favicon-32x32.png username@arex.co.ke:/path/to/website/"
echo ""
echo "Common paths:"
echo "- /var/www/html/"
echo "- /home/username/public_html/"
echo "- /var/www/arex.co.ke/"
echo ""
echo "Example:"
echo "scp favicon* user@arex.co.ke:/var/www/html/"
