github.com:
    users:
        Juganu953:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Juganu953
